### ISSUE TITLE
Repo is public when it should be private

### ISSUE THREAD

**Issue by jahsome** [paracore/project-bootstrap#4]
Hey guys, I was trolling around and noticed I still have access to this repo even though I'm not part of the paracore group/team anymore. Just figured you may wanna know.

**Comment by paracore-admin** [comment]
"Public forks can’t be made private." It says to dupe it instead. :( We have failed.

**Comment by jahsome** [comment]
Ah well just a heads up in that case--just don't put any proprietary info in here and you guys should be good.
